@"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe"^
	"Tests\Centurion.Application.Tests\bin\Release\AH.TSO.Centurion.Application.Tests.dll"^
	"Tests\Centurion.GUI.Tests\bin\Release\AH.TSO.Centurion.GUI.Tests.dll"^
	"Tests\Common.Tests\bin\Release\AH.TSO.Common.Tests.dll"^
	"Tests\Database.Tests\bin\Release\AH.TSO.Database.Tests.dll"^
	"Tests\Optimisation.Tests\bin\Release\AH.TSO.Optimisation.Tests.dll"^
	"Tests\Simulation.Tests\bin\Release\AH.TSO.Simulation.Tests.dll"^
	"Tests\Centurion.GUI.Tests\bin\Release\AH.TSO.Centurion.GUI.Tests.dll"
@pause
